feat: MainController 작성
f-lab-edu/TicketEase pull request #6
Opened 2023-08-30 12:12 UTC by smh0300

pr coverage 테스트

2023-08-30 14:31 UTC, kochungcheon approved these changes

2023-08-30 14:36 UTC, kochungcheon requested changes
merge를 main이 아닌 develop 에 해야 할 거 같아요!

2023-08-30 16:37 UTC, kochungcheon approved these changes

2023-08-31 14:15 UTC, heeve1 approved these changes
심플하군요 고생하셨습니다 민혁님

2023-08-31 14:15 UTC, heeve1 commented on src/test/java/com/Ticketease/TE/main/MainControllerTest.java
> +    private MockMvc mvc;
controller 테스트로 아주 좋군요 코드가 변경됨에 따라 잘 발전시켜 나가면 좋을 것 같습니다~

2023-09-01 10:06 UTC, merged